// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_cj433.Models;

namespace Mission06_cj433.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20230221234503_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_cj433.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Western"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Romance/Drama"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Sci-Fi"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Animation"
                        });
                });

            modelBuilder.Entity("Mission06_cj433.Models.FormResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Director = "Matt Reaves",
                            Edited = false,
                            LentTo = "",
                            Notes = "This was my favorite movie in 2022.",
                            Rating = "PG-13",
                            Title = "The Batman",
                            Year = (short)2022
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 2,
                            Director = "Sergio Leone",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Once Upon a Time in the West",
                            Year = (short)1968
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 1,
                            Director = "Ridley Scott",
                            Edited = true,
                            LentTo = "Olivia Jensen",
                            Notes = "This is one of my favorites!",
                            Rating = "R",
                            Title = "Gladiator",
                            Year = (short)2000
                        });
                });

            modelBuilder.Entity("Mission06_cj433.Models.FormResponse", b =>
                {
                    b.HasOne("Mission06_cj433.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
